services:
  db-payroll:
    image: mysql:8.0
    container_name: db-payroll
    restart: always
    environment:
      MYSQL_DATABASE: payroll_db
      MYSQL_ROOT_PASSWORD: ${DB_PASS_ROOT}
      MYSQL_USER: ${DB_USER}        # El usuario que usará tu App Spring Boot
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "3306:3306" # Solo si necesitas conectar desde afuera (ej. Workbench)
    volumes:
      - ./mysql_data:/var/lib/mysql

  payroll-service:
    build: .
    container_name: payroll-app
    ports:
      - "8084:8084"
    restart: always
    environment:
      # Aquí usas la IP pública o el host que te de Hostinger para MySQL
      - SPRING_DATASOURCE_URL=jdbc:mysql://${DB_NAME}?useSSL=false
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASS}
      - APPLICATION_SECURITY_JWT_SECRET_KEY=${JWT_SECRET_KEY}